### ISSUE TITLE
Sculk balancing suggestions

### ISSUE THREAD

**Issue by ByThePowerOfScience** [FakeACat/FromAnotherWorld-Architectury#12]
The general balance of the mod is really good, but the sculk is a bit tough to counter.  A few changes would make it so much more balanced of a battle:

## Spread tweaks:

- Make spreading only start from catalysts, so breaking the catalyst halts the spread until a new one spawns.
- Make sculk only spread along surfaces instead of through walls, like how sculk spreads normally.
- Make new catalysts only spawn during a spread wave so you have a _chance_ of fighting it off completely.
  - Since assimilated sculk isn't flammable (so there's no non-manual way to stop its advance), the only way to fight it is to break it by hand, which takes _much_ longer than it takes to spread. Even with instamine and four people, it was an impossible battle since its spread waves are so massive.  The ability to pause the waves will make it at all possible to wipe out completely, even if it is a tremendous effort.

## Shrieker balancing:

Shriekers specifically are completely impossible to battle at the moment, since they become a massive impenetrable bubble that regenerates too fast to clear and expands infinitely outwards, triggering other shriekers as it goes.  With a few minor tweaks though, it would be a very interesting fight instead of a world-destroying obstacle.

- Make shrieker brambles no longer trigger other shriekers.
- **Make brambles decay** after the cloud reaches full size, making them more of a temporary hazard to triggering sculk rather than a permanent ball of death.
  - If you don't want to make them decay, make them flammable at least and/or make the sound of them being destroyed not trigger the shrieker they came from.  Right now it's impossible to get to the shrieker to stop the ball of death because they regenerate too quickly.
- Prevent shriekers from spawning within each others' bramble ranges so they don't set off a constant wall of brambles that never disappears.
- Prevent shriekers and shrieker brambles from spawning underwater so they don't permanently remove huge swathes of water.
- Prevent shrieker brambles from spawning other shriekers inside of it.

**Comment by FakeACat** [comment]
You probably already saw the note at the top of the curseforge page and because of that I don't really want to massively rebalance anything at this point. I'm aware that it's way too hard though so assimilated sculk will be optional and disabled by default in the next update. That being said, a lot of these suggestions are surprisingly close to how it works currently.

It spreads exactly like vanilla sculk, with the only differences being that catalysts/tentacles randomly create spreaders instead of when mobs are killed nearby and it assimilates vanilla sculk that it touches. 

Assimilated sculk detects you only using sight, not sound. I tried to make this clear by making the sensors eyes that follow you but in the chaos it can be hard to notice. As long as no assimilated sculk sensors can see you, the brambles will not grow and they will gradually decay. Since assimilated sculk sensors don't detect sound at all, shriekers can't trigger themselves or other nearby shriekers.
